# permissions for end users to view bananas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: banana-viewer-role
rules:
- apiGroups:
  - fruits.com
  resources:
  - bananas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fruits.com
  resources:
  - bananas/status
  verbs:
  - get
