name: test-operator
on: [ push ]
jobs:
  build-and-test-operator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.5'
      - run: kind create cluster
      # Build the Docker image and load it into Kind
      # Don't forget to remove the "test" step from "docker-build" target in Makefile - we'll run the tests separately
      - run: export IMG='banana-controller:v1'; make docker-build
      - run: kind load docker-image banana-controller:v1
      # Deploys the image by applying manifests from config/crd, config/rbac and config/manager
      - run: export IMG='banana-controller:v1'; make deploy
      # Wait for the controller application to start
      - run: sleep 20
      # Run tests
      - run: export USE_EXISTING_CLUSTER=true; make test
