name: test-operator
on: [ push ]
jobs:
  build-and-test-operator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.5'
      - run: chmod +x ops/scripts/launch-kind.sh; ./ops/scripts/launch-kind.sh
      # Apply CustomResourceDefinition from config/crd
      - run: make install
      # Build the Docker image and push it into the local registry (set up with Kind)
      # Don't forget to remove the "test" step from "docker-build" target in Makefile - we'll run the tests separately
      - run: export IMG='localhost:5000/banana-controller:latest'; make docker-build; make docker-push
      # Deploys the image by applying manifests from config/crd, config/rbac and config/manager
      - run: export IMG='localhost:5000/banana-controller:latest'; make deploy
      - run: sleep 4
      - run: kubectl get deploy banana-operator-golang-controller-manager -n banana-operator-golang-system -o yaml
      # Run tests
      - run: export USE_EXISTING_CLUSTER=true; make test
