name: test-operator
on: [ push ]
jobs:
  build-and-test-operator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.5'
      - run: chmod +x ops/scripts/launch-kind.sh; ./ops/scripts/launch-kind.sh
      - run: export USE_EXISTING_CLUSTER=true; make test
